name: Linux

on: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Compile
      run: nodejs_bin/node-linux64 Kromx/make.js -g opengl
    - name: cd
      run: cd Kromx 
    - name: Compile
      run: nodejs_bin/node-linux64 Kinc/make.js -g opengl --compiler clang --compile
    - name: cd
      run: cd Deployment
    - name: strom
      run: strip Krom
