name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: node Kromx/make.js -g direct3d11
      run: cd Kromx 
      run: node Kinc/make -g direct3d11
