name: windows

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile kromx
      run: node Kromx/make.js -g direct3d11
    - name: Cd
      run: cd Kromx 
    - name: Compile kinc
      run: node Kinc/make -g direct3d11
